// Embeds ../../index.html into a JS module so the Expo WebView can load the
// lesson app without any bundling/asset-copy step. Re-run whenever index.html
// changes (this also runs automatically via the "prestart" npm script).
const fs = require('fs');
const path = require('path');

const SOURCE_HTML = path.join(__dirname, '..', '..', 'index.html');
const OUTPUT_FILE = path.join(__dirname, '..', 'assets', 'web', 'webAppHtml.js');

const html = fs.readFileSync(SOURCE_HTML, 'utf8');

// Escape characters that would break out of a JS template literal.
const escaped = html
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${');

const banner = '// AUTO-GENERATED by scripts/sync-html.js from ../index.html. Do not edit by hand.\n';
const contents = banner + 'export const WEB_APP_HTML = `' + escaped + '`;\n';

fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
fs.writeFileSync(OUTPUT_FILE, contents);

console.log('Synced index.html -> ' + path.relative(process.cwd(), OUTPUT_FILE) + ' (' + html.length + ' bytes)');
